list_of_classes = sorted([ "Barbarian",
                    # "Bard",
                    # "Cleric",
                    # "Druid",
                    "Fighter",
                    "Monk",
                    "Paladin",
                    "Ranger",
                    "Rogue",
                    # "Sorcerer",
                    # "Warlock",
                    # "Wizard",
                    # "Artificer",
                    ])

dict_of_subclasses = {
    "Barbarian": ["Path of the Ancestral Guardian",
                "Path of the Battlerager",
                "Path of the Beast",
                "Path of the Bersker", 
                "Path of the Totem Warrior",
                "Path of the Storm Herald",
                "Path of Wild Magic",
                "Path of the Zealot"],
    "Fighter": ["Arcane Archer",
                "Cavalier",
                "Champion", 
                "Battle Master",
                "Echo Knight", 
                "Eldritch Knight",
                "Psi Warrior",
                "Purple Dragon Knight",
                "Rune Knight",
                "Samurai",],
    "Monk": ["Way of the Open Hand", 
                "Way of the Drunken Master",
                "Way of Shadow", 
                "Way of the Four Elements",               
                "Way of the Long Death",
                "Way of the Sun Soul",
                "Way of the Kensei"
                "Way of Mercy",
                "Way of the Astral Self",],
    "Paladin": ["Oath of Conquest",
                "Oath of Devotion",
                "Oath of Glory", 
                "Oath of the Ancients",
                "Oath of the Crown",
                "Oath of Redemption", 
                "Oath of Vengeance",
                "Oathbreaker",
                "Oath of the Watchers",],
    "Ranger": ["Hunter", 
                "Beast Master",
                "Gloom Stalker",
                "Horizon Walker",
                "Monster Slayer",
                "Fey Wanderer",
                "Swarmkeeper",],
    "Rogue": ["Thief",
                "Assassin",
                "Arcane Trickster",
                "Mastermind",
                "Swashbuckler",
                "Inquisitive",
                "Scout",
                "Phantom",
                "Soulknife"],
    
    
}
